blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'


urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:blog_id>/', views.detail,  name='detail'),
]

portfolio_osobiste/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('',views.home, name='home'),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):
    tytul = models.CharField(max_length=250)
    description = models.TextField()
    date = models.DateField()

    def __str__(self):
        return self.tytul

portfolio/models.py
from django.db import models

# Create your models here.

class Project(models.Model):
    title = models.CharField(max_length=200)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='yes')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import  render, get_object_or_404
from .models import Blog
# Create your views here.

def all_blogs(request):

     blogs = Blog.objects.order_by('-date')
     return render(request,'blog/all_blogs.html',{'blogs':blogs})

def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/detail.html',{'blog':blog})

portfolio/views.py
from django.shortcuts import render
from .models import Project
# Create your views here.
def home(request):
    projects = Project.objects.all()
    return render(request,"portfolio/home.html", {'projects':projects})

blog/templates/blog/all_blogs.html

{% extends 'portfolio/base.html' %}

{% load static %}

{% block content %}

<h1 id="blogtitle" class="font-weight-bold text-center">Blog</h1>
    

<h2 class="text-center mb-5">Michał wrote {{blogs.count}} blog{{blogs.count|pluralize}}</h2>

{% for blog in blogs %}
<div class="row justify-content-center my-3">
    <div class="col-md-10">
        <a href="{% url 'blog:detail' blog.id %}"><h1>{{blog.tytul}}</h1></a>
        <h5 class="text-muted">{{blog.date|date:'M d y'|upper}}</h5>
        <p>{{blog.description|striptags|truncatechars:100}}</p>
    </div>
</div>
{% endfor %}

{% endblock %}


blog/templates/blog/detail.html

{% extends "portfolio/base.html" %}

{% load static %}

{% block content %}


<h1 class="text-center mt-5" id="blogdetailtitle">{{ blog.tytul }}</h1>

<h5 class="text-center text-muted mb-5">--{{blog.date|date:'F jS Y'}}--</h2>


<p class="text-center mt-5">{{blog.description|safe}}</p> 

{% endblock %}

portfolio/templates/portfolio/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  <link rel="stylesheet" href="{% static "portfolio/custom.css" %}">

  <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">

  <link rel="icon" type="image/png" href="{% static "portfolio/logo.png" %}">

  <title>Michał Bodura</title>
</head>

<body>

<nav id="topNav" class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home' %}">
        <img src="{% static "portfolio/logo.png" %}" width="30" height="30" class="d-inline-block align-top" alt="Nick's Logo">
        <span>Michał Bodura</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="{% static "portfolio/BoduraMichał_CV.pdf" %}">CV</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://www.linkedin.com/in/micha%C5%82-bodura-951462173/" target="_blank">LinkedIn</a>
          </li>
          <li>
            <a role="button" href="{% url 'blog:all_blogs' %}" class="btn btn-primary">Blog</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    {% block content %}{% endblock %}
  </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</body>

</html>

portfolio/templates/portfolio/home.html

    {% extends 'portfolio/base.html' %}

    {% load static %}

    {% block content %}
    
    
    <div class="row justify-content-center my-3">
    <div class="col-5">
        <img src="{% static 'portfolio/Profilowe2.png' %}" class="img-fluid">
        </div>
    </div>  
    <hr>
    <h1 class="mt-5">Moje portfolio</h1>

    <hr>

    <div class = "row">
    {% for project in projects %}
        <div class="col-lg-4 col-md-6">
            <h2>{{ project.title }}</h2>
            <p>{{ project.description }}</p>
            <img src="{{project.image.url}}" class="img-fluid mb-2">

            <br>
            <a href="{{project.url}}" class="btn btn-primary">Mój link</a>
        </div>
        {% endfor %}
    
    </div>
    {% endblock %}